### ISSUE TITLE
关于开发 和 登录

### ISSUE THREAD

**Issue by xiaololo007** [emailtohl/web-building#1]
系统我在本地部署成功了，切换到了mysql 数据库，我使用的是idea 来开发，现在不知道应该怎么样去开发启动，登录一直都没有成功

**Comment by emailtohl** [comment]
你好，这是我个人的学习项目，有些地方是为了验证功能所以做得较为复杂，也有可能没有说明清楚。
请见README.MD文件中的“2.2 创建数据库”，在com.github.emailtohl.building.initdb.PersistenceData中，预留了一些账号相关的初始化数据，例如可以通过emailtohl@163.com/123456登录。

这里面还是用了很多方面的技术，有不明白的地方，可以探讨我的QQ：1940435432
